### PR TITLE
Pop3 certificate options

### PR DESCRIPTION
**Pull request by ChinthakaSenanayaka**
README fix, Please review

Please make this available in NPM

### CODE REVIEW

**Review by agsh — APPROVED** [review]

**Comment by agsh** [comment]
@ChinthakaSenanayaka I've changed a bit API in the `master` branch. Plz, look at my recent changes. If this ok for you, I'll publish it.

**Comment by ChinthakaSenanayaka** [comment]
@agsh: connect function options should get precedence than constructor options.

README.md optional - object - Optional configuration JSON object for socket creation. (see. TLS and NET). This should be `options` than optional. 

Thanks, I am good with changes

**Comment by agsh** [comment]
@ChinthakaSenanayaka 

> connect function options should get precedence than constructor options.

Yes, it is. https://github.com/agsh/yapople/blob/master/lib/yapople.js#L221. I wrote something incomprehensible in the README? :smile: 

> README.md optional - object - Optional configuration JSON object for socket creation. (see. TLS and NET). This should be options than optional.

:+1:

**Comment by agsh** [comment]
@ChinthakaSenanayaka done

**Pull request merged**
